//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseForm
    {
        public int ResponseFormID { get; set; }
        public int FormId { get; set; }
        public string FormName { get; set; }
        public string UserEmail { get; set; }
        public string Name { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
